SELECT c.ITEM_ID, c.ITEM_NAME, c.RARITY
FROM ITEM_TREE t
JOIN ITEM_INFO p ON p.ITEM_ID = t.PARENT_ITEM_ID      -- 부모(RARE인지 확인)
JOIN ITEM_INFO c ON c.ITEM_ID = t.ITEM_ID             -- 자식(출력 대상)
WHERE p.RARITY = 'RARE'
ORDER BY c.ITEM_ID DESC;