-- 코드를 입력하세요
SELECT a.TITLE, a.BOARD_ID,b.REPLY_ID, b.WRITER_ID, b.CONTENTS, DATE_FORMAT(b.CREATED_DATE, "%Y-%m-%d") as CREATED_DATE
FROM USED_GOODS_BOARD a
JOIN USED_GOODS_REPLY b ON  a.BOARD_ID = b.BOARD_ID
where a.CREATED_DATE >= '2022-10-01' AND a.CREATED_DATE < '2022-11-01'
ORDER BY b.CREATED_DATE ASC, a.TITLE ASC